<?php

namespace ContainerZ86TmE8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ik6O0dsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ik6O0ds' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ik6O0ds'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'date' => ['privates', '.errored..service_locator.ik6O0ds.DateTimeInterface', NULL, 'Cannot autowire service ".service_locator.ik6O0ds": it references interface "DateTimeInterface" but no such service exists. Did you create a class that implements this interface?'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'date' => 'DateTimeInterface',
            'entityManager' => '?',
        ]);
    }
}
