<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWiTNLOg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWiTNLOg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWiTNLOg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWiTNLOg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWiTNLOg\App_KernelDevDebugContainer([
    'container.build_hash' => 'WiTNLOg',
    'container.build_id' => '360dc9fa',
    'container.build_time' => 1700410835,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWiTNLOg');
